id: P4BDF7893
initial_creation_type: ocr
source_metadata:
  volumes:
    177c269f78874f6abecedbaa3225255d:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་ནག་པོ་ཆེན་པོའི་བསྟོད་པ་རྐང་པ་བརྒྱད་པ།
      total_pages: 1856
      volume_number: 14
